#!/bin/bash
app=opendkim

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
is_public=$(sudo yunohost app setting $app is_public)
final_path=/var/www/$path


# Removal of web page
sudo rm -rf $final_path

# Suppression de la config nginx de la webapp
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Remove software and conf files
sudo apt-get -y remove opendkim opendkim-tools
sudo rm -rf /etc/opendkim*

# Cleaning of /etc/default/opendkim
#sed -i '/SOCKET=\"inet:8891@localhost\"/d' /etc/default/opendkim
sudo rm /etc/default/opendkim

# Removal of the milter in postfix main.cf (unknown at this stage)
postfix=/etc/postfix/main.cf
sudo sed -i '/# Opendkim milter configuration/d' /etc/postfix/main.cf
sudo sed -i '/milter_protocol = 2/d' /etc/postfix/main.cf
sudo sed -i '/milter_default_action = accept/d' /etc/postfix/main.cf
sudo sed -i '/smtpd_milters = inet:127.0.0.1:8891/d' /etc/postfix/main.cf
sudo sed -i '/non_smtpd_milters = inet:127.0.0.1:8891/d' /etc/postfix/main.cf

# Restart services
sudo service postfix reload
sudo service nginx reload
sudo yunohost app ssowatconf
